return {
	"MagicDuck/grug-far.nvim",
	opts = {
		headerMaxWidth = 80,
		wrap = false,
		windowCreationCommand = "topleft vsplit",
		keymaps = {
			qflist = { n = "<localleader>q" },
			syncLocations = { n = "<localleader>s" },
			syncLine = { n = "<tab>" },
			close = { n = "<localleader>c" },
			historyOpen = { n = "<localleader>t" },
			historyAdd = { n = "<localleader>a" },
			refresh = { n = "<localleader>f" },
			openLocation = { n = "<localleader>o" },
			openNextLocation = { n = "<down>" },
			openPrevLocation = { n = "<up>" },
			gotoLocation = { n = "<enter>" },
			pickHistoryEntry = { n = "<enter>" },
			abort = { n = "<localleader>b" },
			help = { n = "g?" },
			toggleShowCommand = { n = "<localleader>p" },
			swapEngine = { n = "<localleader>e" },
			previewLocation = { n = "<localleader>i" },
			swapReplacementInterpreter = { n = "<localleader>x" },
			applyNext = { n = "<localleader>j" },
			applyPrev = { n = "<localleader>k" },
		},
	},
}
